// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "grdisplayviewer1.h"

/////////////////////////////////////////////////////////////////////////////
// CGrdisplayviewer1

IMPLEMENT_DYNCREATE(CGrdisplayviewer1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGrdisplayviewer1 properties

/////////////////////////////////////////////////////////////////////////////
// CGrdisplayviewer1 operations
